name: "Copilot Setup Steps"

on: workflow_dispatch
jobs:
  # This is the required job name. If different, Copilot will ignore it.
  copilot-setup-steps:
    runs-on: ubuntu-latest
 
  # Starts a MongoDB service for Copilot to use during its session.
    services:
     mongo:
       image: mongo:7
       ports:
         - 27017:27017

    # Grant Copilot early access to read the repository content.
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
